### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [CleverChuk/mips-simulator#1]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

Could you please in the meantime attach a signed release apk to your [releases](https://github.com/CleverChuk/mips-simulator/releases), so that people can easily download your app?

**Comment by CleverChuk** [comment]
The app itself is not a FOSS. However, the compiler backend which is to be consumed as a library is. This repo is the compiler backend.

**Comment by Poussinou** [comment]
Ok sorry I was mistaken. Gonna close this, since it's not relevant.

Thanks for your answer 👍
